version: '3'

services:

  nginx:
    build: nginx
    container_name: proxy
    depends_on:
      - db
    ports:
      - "8080:80"
    networks: 
      - challenge

  app:
    build: app
    container_name: app
    depends_on:
      - db
    expose:
      - "8080"
    networks: 
      - challenge

  db:
    image: "mysql:5.7"
    container_name: db
    environment:
      # - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpwd
    volumes:
      - ./db/current/v20180328.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - challenge

networks:
  challenge:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"